// <auto-generated />
using System;
using LoginApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoginApi.Model.AddBuySellRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BuyDocFeeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyDocFeeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyOtherJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyOtherUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySealJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySealUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySurrChargeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySurrChargeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTHCOriginJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTHCOriginUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTotalJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTotalUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyoceanfreightJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyoceanfreightUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractSpotType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalPlaceDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JPYRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellDocFeeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellDocFeeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellOtherJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellOtherUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSealJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSealUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSurrChargeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSurrChargeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTHCOriginJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTHCOriginUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTotalJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTotalUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelloceanfreightJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelloceanfreightUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("USDRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidityFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidityTo")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BuySellRate");
                });

            modelBuilder.Entity("LoginApi.Model.MasterTable", b =>
                {
                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContainerSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractSpotType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer");

                    b.ToTable("MasterTable");
                });

            modelBuilder.Entity("LoginApi.Model.SellRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BuyDocFeeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyDocFeeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyOtherJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyOtherUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySealJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySealUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySurrChargeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuySurrChargeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTHCOriginJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTHCOriginUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTotalJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyTotalUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyoceanfreightJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyoceanfreightUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractSpotType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalPlaceDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JPYRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellDocFeeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellDocFeeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellOtherJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellOtherUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSealJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSealUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSurrChargeJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellSurrChargeUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTHCOriginJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTHCOriginUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTotalJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellTotalUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelloceanfreightJPY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelloceanfreightUSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USDRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidityFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidityTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SellRate");
                });

            modelBuilder.Entity("LoginApi.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
